title: Developers
propertytitle: A guide to using the Apollo platform
description: A guide to using the Apollo platform
versions:
  - '1'
sidebar_categories:
  null:
    - index
    - intro/platform
    - intro/benefits

  Tutorial:
    - tutorial/introduction
    - tutorial/schema
    - tutorial/data-source
    - tutorial/resolvers
    - tutorial/production
    - tutorial/client
    - tutorial/queries
    - tutorial/mutations
    - tutorial/local-state
    # - tutorial/whats-next

  Platform:
    - platform/schema-design
    - platform/schema-registry
    # - platform/client-awareness
    - platform/schema-validation
    - platform/operation-registry
    - platform/editor-plugins
    - platform/tracing
    - platform/errors
    - platform/integrations

  Resources:
    - resources/apollo-config
    - resources/graphql-glossary
    - resources/faq

  Documentation:
    - title: Apollo Client
      href: https://www.apollographql.com/docs/react/
    - title: Apollo Server
      href: https://www.apollographql.com/docs/apollo-server/v2/
    - title: Apollo Engine
      href: https://www.apollographql.com/docs/engine/
github_repo: apollographql/apollo
content_root: docs/source

url: https://www.apollographql.com/docs
root: /docs/

public_dir: public/docs