title: Platform
propertytitle: How to use the Apollo GraphQL platform
description: How to use the Apollo GraphQL platform
versions:
  - '1'
sidebar_categories:
  null:
    - index
    - intro/platform
    - intro/benefits

  Tutorial:
    - tutorial/introduction
    - tutorial/schema
    - tutorial/data-source
    - tutorial/resolvers
    - tutorial/production
    - tutorial/client
    - tutorial/queries
    - tutorial/mutations
    - tutorial/local-state
    # - tutorial/whats-next

  Platform:
    - platform/apollo-config
    - platform/schema-registry
    - platform/client-awareness
    - platform/schema-validation
    - platform/operation-registry
    - platform/editor-plugins
    - platform/tracing
    - platform/errors
    - platform/integrations

  Resources:
    - resources/graphql-glossary
    - resources/faq
    - references/apollo-engine
    - references/engine-proxy

github_repo: apollographql/apollo
content_root: docs/source

url: https://www.apollographql.com/docs
root: /docs/

public_dir: public/docs
