title: Developers
propertytitle: Add GraphQL to your stack and start building apps faster.
subtitle:
description: A guide to using the Apollo platform.
versions:
  - '1'
sidebar_categories:
  null:
    - index
  Fundamentals:
    - fundamentals/platform
    - fundamentals/benefits
    - fundamentals/tips
  Guides:
    - guides/schema-design
    - guides/versioning
    - guides/security
    - guides/access-control
    - guides/monitoring
    - guides/state-mgmt
  Documentation:
    - title: Apollo Client
      href: https://www.apollographql.com/docs/react/
    - title: Apollo Server
      href: https://www.apollographql.com/docs/apollo-server/v2/
    - title: Apollo Engine
      href: https://www.apollographql.com/docs/engine/
github_repo: apollographql/apollo
content_root: docs/source

url: https://www.apollographql.com/docs
root: /docs/

public_dir: public/docs
